// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZqFU0v5AZ7YIf9dyzK2fIk1XSIsT3e40',
    appId: '1:553448506117:web:8f53b6e7963041a725ed6c',
    messagingSenderId: '553448506117',
    projectId: 'giveit-away-5ebfb',
    authDomain: 'giveit-away-5ebfb.firebaseapp.com',
    storageBucket: 'giveit-away-5ebfb.firebasestorage.app',
    measurementId: 'G-W33JVC4JJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoOKhY0DNzn1d9fp_MyT6FKuN_xe1s_tw',
    appId: '1:553448506117:android:283201c87fc6363525ed6c',
    messagingSenderId: '553448506117',
    projectId: 'giveit-away-5ebfb',
    storageBucket: 'giveit-away-5ebfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFVe-4m7YZ9QOYrpPewUmgZNb_1Nxu0jk',
    appId: '1:553448506117:ios:5829378b4523122525ed6c',
    messagingSenderId: '553448506117',
    projectId: 'giveit-away-5ebfb',
    storageBucket: 'giveit-away-5ebfb.firebasestorage.app',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFVe-4m7YZ9QOYrpPewUmgZNb_1Nxu0jk',
    appId: '1:553448506117:ios:5829378b4523122525ed6c',
    messagingSenderId: '553448506117',
    projectId: 'giveit-away-5ebfb',
    storageBucket: 'giveit-away-5ebfb.firebasestorage.app',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZqFU0v5AZ7YIf9dyzK2fIk1XSIsT3e40',
    appId: '1:553448506117:web:dc97909088ea45a725ed6c',
    messagingSenderId: '553448506117',
    projectId: 'giveit-away-5ebfb',
    authDomain: 'giveit-away-5ebfb.firebaseapp.com',
    storageBucket: 'giveit-away-5ebfb.firebasestorage.app',
    measurementId: 'G-E0VL6XB0XQ',
  );
}
